(()=>{
'use strict';
const $=s=>document.querySelector(s), esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const ROLE={benevole:'Bénévole',referent:'Référent',admin:'Organisation'};
const ICON={Accueil:'⌂','Mes créneaux':'▦',Planning:'▤',Contacts:'♧',Équipe:'♙',Véhicules:'▰',Messages:'✉',Outils:'⚙',Préparation:'◷',Formulaires:'▧',Simulations:'⟳',Arbitrages:'◇',Rotations:'↻',Contrôles:'✓',Validation:'◉',Publication:'↗',Terrain:'⌖'};
const NAV={benevole:[['Accueil','home'],['Mes créneaux','myshifts'],['Planning','planning'],['Contacts','contacts']],referent:[['Accueil','home'],['Équipe','team'],['Véhicules','vehicles'],['Planning','planning'],['Messages','messages'],['Contacts','contacts'],['Outils','tools']],admin:[['Préparation','setup'],['Formulaires','forms'],['Simulations','simulations'],['Planning','planning'],['Arbitrages','arbitrations'],['Rotations','rotations'],['Contrôles','checks'],['Validation','validation'],['Publication','publication'],['Terrain','terrain'],['Véhicules','vehicles'],['Messages','messages'],['Contacts','contacts']]};
const TABLE={team:'BENEVOLES',contacts:'BENEVOLES',myshifts:'PLANNING',planning:'PLANNING',forms:'FORMULAIRES',simulations:'SIMULATIONS',arbitrations:'ARBITRAGES',rotations:'ROTATIONS',checks:'ANOMALIES',validation:'ANOMALIES',publication:'PUBLICATION',terrain:'ETAT_TERRAIN',vehicles:'VEHICULES',messages:'MESSAGES'};
const META={home:['MON FESTIVAL','Votre espace bénévoles','Les informations pratiques pour préparer votre édition.'],myshifts:['MON ENGAGEMENT','Mes créneaux','Retrouve tes missions et tes horaires.'],planning:['ORGANISATION','Planning général','Consulte les affectations publiées.'],contacts:['CARNET D’ÉQUIPE','Contacts','Les personnes utiles pendant le festival.'],team:['ÉQUIPE','Bénévoles','Référents et équipe de l’édition.'],vehicles:['LOGISTIQUE','Véhicules','Parc, départs et retours des véhicules.'],messages:['INFORMATIONS','Messages','Consignes et actualités de l’équipe.'],tools:['ESPACE RÉFÉRENT','Outils','Accès aux modules de suivi.'],setup:['CYCLE DE L’ÉDITION','Préparation','Paramètres généraux et progression de la nouvelle édition.'],forms:['INSCRIPTIONS','Formulaires','Ouverture et suivi des disponibilités.'],simulations:['AFFECTATIONS','Simulations','Construire puis comparer les propositions de planning.'],arbitrations:['DÉCISIONS','Arbitrages','Traiter les demandes et les points à décider.'],rotations:['ÉQUILIBRE','Rotations','Vérifier la répartition des missions et des horaires.'],checks:['QUALITÉ','Contrôles','Repérer et résoudre les anomalies.'],validation:['AVANT PUBLICATION','Validation','Faire les dernières vérifications du planning.'],publication:['MISE EN LIGNE','Publication','Publier la version retenue du planning.'],terrain:['PENDANT LE FESTIVAL','Suivi terrain','Suivre les créneaux et changements sur place.']};
let session=null,cache={},page='home';
async function api(action,data={}){const base=window.BEAUREGARD_CONFIG?.API_URL||'';if(!base||base.includes('COLLER_ICI'))throw Error('Le lien Apps Script V2 n’est pas encore configuré.');const requestId=`${Date.now()}-${Math.random().toString(36).slice(2)}`;return new Promise((resolve,reject)=>{const frame=document.createElement('iframe'),form=document.createElement('form'),target=`beauregard_api_${requestId.replace(/[^a-zA-Z0-9_]/g,'')}`;frame.name=target;frame.style.display='none';form.method='POST';form.action=base;form.target=target;form.style.display='none';const input=document.createElement('input');input.type='hidden';input.name='payload';input.value=JSON.stringify({action,token:session?.token||'',data,requestId});form.appendChild(input);const cleanup=()=>{clearTimeout(timer);window.removeEventListener('message',onMessage);form.remove();frame.remove()};const timer=setTimeout(()=>{cleanup();reject(Error('Le serveur Apps Script ne répond pas après 60 secondes.'))},60000);const onMessage=e=>{if(e.source!==frame.contentWindow)return;const out=e.data;if(!out||out.requestId!==requestId)return;cleanup();if(!out.ok){reject(Error(out.error||'Erreur serveur'));return}resolve(out.data)};window.addEventListener('message',onMessage);document.body.append(frame,form);form.submit()})}
function notice(msg,type='info'){const n=$('#appNotice');n.textContent=msg;n.classList.remove('hidden');n.dataset.type=type;setTimeout(()=>n.classList.add('hidden'),6500)}
function setTitle(){let [ey,title,sub]=META[page]||META.home;$('#pageEyebrow').textContent=ey;$('#pageTitle').textContent=title;$('#pageSubtitle').textContent=sub;$('#pageCrumb').textContent=title;document.title=title+' — Beauregard'}
function nav(){let items=NAV[session.role]||NAV.benevole;const make=([label,key])=>`<button class="nav-link ${page===key?'active':''}" data-page="${key}"><span class="nav-icon">${ICON[label]||'•'}</span><span>${esc(label)}</span></button>`;$('#desktopNav').innerHTML=items.map((it,i)=>`${session.role==='admin'&&i===0?'<div class="nav-group-label">Cycle édition</div>':''}${session.role==='referent'&&i===1?'<div class="nav-group-label">Équipe & ressources</div>':''}${make(it)}`).join('');$('#mobileNav').innerHTML=items.filter((_,i)=>session.role!=='admin'||i<5).map(make).join('');$('#mobileNav').classList.toggle('scroll-nav',items.length>4);document.querySelectorAll('[data-page]').forEach(b=>b.onclick=()=>go(b.dataset.page))}
function go(key){page=key;nav();setTitle();renderPage()}
function renderTable(rows){if(!rows?.length)return `<div class="empty"><b>Aucune donnée pour le moment</b>Les éléments ajoutés au classeur apparaîtront ici.</div>`;const keys=Object.keys(rows[0]||{}).filter(k=>!k.startsWith('_')).slice(0,7);return `<div class="table-wrap"><table><thead><tr>${keys.map(k=>`<th>${esc(k.replaceAll('_',' '))}</th>`).join('')}</tr></thead><tbody>${rows.map(r=>`<tr>${keys.map(k=>`<td>${esc(r[k])}</td>`).join('')}</tr>`).join('')}</tbody></table></div>`}
function buttons(actions){return actions.map(([label,act,cls='secondary'])=>`<button class="button ${cls}" data-action="${act}">${label}</button>`).join('')}
function card(title,body,extra=''){return `<article class="card"><h2>${title}</h2>${body}${extra}</article>`}
async function renderPage(){const c=$('#pageContent');c.innerHTML='<div class="loading">Chargement de ton espace…</div>';try{if(page==='home'){const data=await api('home');$('#editionLabel').textContent=data.edition?.nom_edition||'NOUVELLE ÉDITION';c.innerHTML=`<div class="hero-card"><div><p class="eyebrow">${esc(data.edition?.annee||'BEAUREGARD')}</p><h2>Une édition se construit ensemble.</h2><p>Retrouve ici ton planning, les consignes et les nouvelles de l’équipe.</p></div><span class="hero-date">${esc(data.edition?.etat_preparation||'EN PRÉPARATION')}</span></div><div class="grid two" style="margin-top:16px">${card('À lire',data.messages?.length?data.messages.map(m=>`<div class="list-row"><div class="list-main"><b>${esc(m.titre)}</b><small>${esc(m.contenu)}</small></div><span class="badge">${esc(m.priorite||'Info')}</span></div>`).join(''):'<p>Aucun message actif.</p>')}${card('Prochain rendez-vous',data.upcoming?.length?data.upcoming.map(x=>`<div class="list-row"><div class="list-main"><b>${esc(x.mission||'Créneau')}</b><small>${esc(x.date||'')} · ${esc(x.heure_debut||'')}</small></div><span class="badge good">Confirmé</span></div>`).join(''):'<p>Ton planning sera affiché dès sa publication.</p>')}</div><div class="stat-row" style="margin-top:16px"><div class="stat"><strong>${data.stats?.members??'—'}</strong><span>Bénévoles</span></div><div class="stat"><strong>${data.stats?.shifts??'—'}</strong><span>Créneaux publiés</span></div><div class="stat"><strong>${data.stats?.vehicles??'—'}</strong><span>Véhicules actifs</span></div></div>`;return}
const table=TABLE[page];if(!table){c.innerHTML=moduleCards();wireActions();return}const res=await api('list',{table});cache[table]=res.rows||[];const admin=session.role==='admin';let acts=[];if((admin||session.role==='benevole')&&page==='myshifts')acts=[['Indiquer mes disponibilités','add','primary']];if((admin||session.role==='referent')&&page==='vehicles')acts=[['Nouvelle réception','reception','primary'],['Ajouter un véhicule','add','secondary']];if(admin&&page==='simulations')acts=[['Nouvelle simulation','simulate','primary']];if(admin&&page==='publication')acts=[['Publier le planning','publish','primary']];if(['terrain','messages','forms'].includes(page)&&(admin||session.role==='referent'))acts=[['Ajouter','add','primary']];const toolbar=`<div class="toolbar"><span class="badge">${(res.rows||[]).length} élément(s)</span><div>${buttons(acts)}</div></div>`;let extra='';if(page==='vehicles'){const rec=await api('list',{table:'RECEPTIONS'});extra=`<div class="section-title" style="margin-top:22px">Réceptions de départ et de retour</div>${renderTable(rec.rows||[])}`}c.innerHTML=toolbar+renderTable(res.rows||[])+extra;wireActions()}catch(e){c.innerHTML=`<div class="empty"><b>Données non disponibles</b>${esc(e.message)}</div>`}}
function moduleCards(){let arr=(NAV[session.role]||[]).filter(x=>x[1]!=='home'&&x[1]!==page);return `<div class="module-grid">${arr.map(([name,key])=>`<button class="module-card" data-page="${key}"><span class="module-icon">${ICON[name]}</span><b>${esc(name)}</b><small>Ouvrir le module et consulter les informations.</small></button>`).join('')}</div>`}
function wireActions(){document.querySelectorAll('[data-action]').forEach(b=>b.onclick=()=>{if(b.dataset.action==='simulate')runAction('simulate',{name:'Simulation '+new Date().toLocaleDateString('fr-FR')},'Simulation créée.');else if(b.dataset.action==='publish')runAction('publish',{},'Planning publié.');else if(b.dataset.action==='add')openAddForm();else if(b.dataset.action==='reception')openReceptionForm()});}
function runAction(act,data,msg){api(act,data).then(()=>{notice(msg,'success');renderPage()}).catch(e=>notice(e.message,'error'))}
function openReceptionForm(){const names=['vehicule_id','sens','conducteur_id','compteur','niveau_carburant','etat_exterieur','etat_interieur','remarques','signataire_remise','signataire_reception','statut'];showForm('RECEPTIONS',names,'Nouvelle réception')}
function openAddForm(){const spec={myshifts:['CHOIX_CRENEAUX','creneau_id,choix,rang'],vehicles:['VEHICULES','immatriculation,marque_modele,type,boite_vitesse,couleur,actif,plein_a_faire,notes'],terrain:['ETAT_TERRAIN','jour,date,etat,note'],messages:['MESSAGES','titre,contenu,cible,priorite,etat,debut,fin'],forms:['FORMULAIRES','titre,etat,date_ouverture,date_fermeture,questions_json']}[page];if(!spec)return;let [table,fields]=spec;let names=fields.split(',');showForm(table,names,'Ajouter à '+table.toLowerCase())}
function showForm(table,names,title){$('#modalRoot').innerHTML=`<div class="modal-backdrop"><div class="modal"><div class="modal-head"><div><p class="eyebrow">NOUVEL ÉLÉMENT</p><h2>${esc(title)}</h2></div><button class="icon-button" data-close aria-label="Fermer">×</button></div><form id="addForm" class="form-grid">${names.map((n,i)=>`<div class="${i===names.length-1?'full':''}"><label>${esc(n.replaceAll('_',' '))}<input name="${esc(n)}" ${/actif|etat/.test(n)?'placeholder="oui / actif"':''} ${['immatriculation','titre'].includes(n)?'required':''}></label></div>`).join('')}<div class="full modal-actions"><button type="button" class="button secondary" data-close>Annuler</button><button class="button primary">Enregistrer</button></div></form></div></div>`;document.querySelectorAll('[data-close]').forEach(x=>x.onclick=()=>$('#modalRoot').innerHTML='');$('#addForm').onsubmit=async e=>{e.preventDefault();const data=Object.fromEntries(new FormData(e.target));try{await api('create',{table,row:data});$('#modalRoot').innerHTML='';notice('Enregistrement effectué.','success');renderPage()}catch(x){notice(x.message,'error')}}}
$('#loginForm').addEventListener('submit',async e=>{e.preventDefault();const err=$('#loginError');err.textContent='Connexion…';try{session=await api('login',{code:$('#accessCode').value});localStorage.setItem('beauregard_v2_session',JSON.stringify(session));start()}catch(x){err.textContent=x.message;session=null}});
function start(){if(!session)return;$('#loginScreen').classList.add('hidden');$('#appShell').classList.remove('hidden');$('#roleLabel').textContent=ROLE[session.role]||'Bénévole';$('#userLabel').textContent=session.name||'Mon espace';$('#userAvatar').textContent=(session.name||'B').trim().slice(0,1).toUpperCase();nav();go('home')}
window.logout=()=>{localStorage.removeItem('beauregard_v2_session');session=null;$('#appShell').classList.add('hidden');$('#loginScreen').classList.remove('hidden');$('#accessCode').value=''};
try{const saved=JSON.parse(localStorage.getItem('beauregard_v2_session')||'null');if(saved?.token)session=saved}catch{}if(session)start();
})();
